export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
#export XDG_CURRENT_DESKTOP="KDE"
#export KDE_SESSION_VERSION="5"
#export QT_QPA_PLATFORMTHEME=kde
export QT_QPA_PLATFORMTHEME=qt5ct
export ZDOTDIR=$XDG_CONFIG_HOME/zsh

for filename in $ZDOTDIR/environment/*.zsh; do
    . $filename
done
