if [[ -v ZSH_PROFILE_STARTUP ]]; then
    zmodload zsh/zprof
fi

skip_global_compinit=1

export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share

for filename in $ZDOTDIR/environment/*.zsh; do
    . $filename
done
